[package]
name = "ophan-net"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["io-util", "net"] }

httparse = { workspace = true }
s2n-tls = { workspace = true }
s2n-tls-tokio = { workspace = true }
http = { workspace = true }
itoa = { workspace = true }
bytes = { workspace = true }
bitflags = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
memchr = { workspace = true }

serde_urlencoded = "0.7"
pingora = { workspace = true, features = ["proxy"] }
async-trait = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
httpmock = { workspace = true }
criterion = { workspace = true }
