pub use http::header::*;

macro_rules! header_names {
    (
        $(
            $(#[$attr:meta])*
            ($const_name:ident, $string_val:expr);
        )*
    ) => {
        $(
            $(#[$attr])*
            pub const $const_name: http::header::HeaderName =
                http::header::HeaderName::from_static($string_val);
        )*
    };
}

macro_rules! header_values {
    (
        $(
            $(#[$attr:meta])*
            ($const_name:ident, $string_val:expr);
        )*
    ) => {
        $(
            $(#[$attr])*
            pub const $const_name: http::header::HeaderValue =
                http::header::HeaderValue::from_static($string_val);
        )*
    };
}

header_names! {
    // =========================================================================
    // Reverse Proxy & Forwarding
    // =========================================================================

    /// Standard header carrying proxy forwarding information.
    ///
    /// This header standardizes the forwarding metadata previously conveyed
    /// by the non-standard `X-Forwarded-*` family. It may include the client
    /// address, original host, and original protocol.
    ///
    /// Specification:
    /// <https://www.rfc-editor.org/rfc/rfc7239>
    ///
    /// Example:
    /// ```http
    /// Forwarded: for=192.0.2.60;proto=https;host=example.com
    /// ```
    (FORWARDED, "forwarded");

    /// Original client IP address as reported by a trusted reverse proxy.
    ///
    /// This is a de facto standard and should only be trusted when received
    /// from known proxy infrastructure.
    ///
    /// Specification:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Forwarded-For>
    ///
    /// Example:
    /// ```http
    /// X-Forwarded-For: 203.0.113.10
    /// ```
    (X_FORWARDED_FOR, "x-forwarded-for");

    /// Original request scheme (`http` or `https`) before reaching the proxy.
    ///
    /// Specification:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Forwarded-Proto>
    ///
    /// Example:
    /// ```http
    /// X-Forwarded-Proto: https
    /// ```
    (X_FORWARDED_PROTO, "x-forwarded-proto");

    /// Original `Host` header received by the reverse proxy.
    ///
    /// Specification:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Forwarded-Host>
    ///
    /// Example:
    /// ```http
    /// X-Forwarded-Host: api.example.com
    /// ```
    (X_FORWARDED_HOST, "x-forwarded-host");

    /// Original destination port before proxy forwarding.
    ///
    /// Example:
    /// ```http
    /// X-Forwarded-Port: 443
    /// ```
    (X_FORWARDED_PORT, "x-forwarded-port");

    /// Original request URI before proxy rewriting.
    ///
    /// Example:
    /// ```http
    /// X-Forwarded-Uri: /api/users
    /// ```
    (X_FORWARDED_URI, "x-forwarded-uri");

    /// Original client IP address.
    ///
    /// Commonly added by NGINX and several reverse proxies.
    ///
    /// Example:
    /// ```http
    /// X-Real-IP: 203.0.113.10
    /// ```
    (X_REAL_IP, "x-real-ip");

    // =========================================================================
    // Observability & Distributed Tracing
    // =========================================================================

    /// Unique request identifier.
    ///
    /// Commonly generated by API gateways and reverse proxies for request
    /// correlation.
    ///
    /// Example:
    /// ```http
    /// X-Request-Id: c96f12cb-fcc0-4a98-a82b-5fd6ffb13d2f
    /// ```
    (X_REQUEST_ID, "x-request-id");

    /// Correlation identifier propagated across services.
    ///
    /// Example:
    /// ```http
    /// X-Correlation-Id: 8ef86b64-9b92-420e-99fa-acde48001122
    /// ```
    (X_CORRELATION_ID, "x-correlation-id");

    /// W3C Trace Context parent identifier.
    ///
    /// Specification:
    /// <https://www.w3.org/TR/trace-context/>
    ///
    /// Example:
    /// ```http
    /// Traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-00
    /// ```
    (TRACEPARENT, "traceparent");

    /// W3C Trace Context vendor-specific state.
    ///
    /// Specification:
    /// <https://www.w3.org/TR/trace-context/>
    (TRACESTATE, "tracestate");

    /// W3C Baggage header for distributed context propagation.
    ///
    /// Specification:
    /// <https://www.w3.org/TR/baggage/>
    ///
    /// Example:
    /// ```http
    /// Baggage: userId=123,tenant=acme
    /// ```
    (BAGGAGE, "baggage");

    // =========================================================================
    // Security
    // =========================================================================

    /// Controls whether a page may be displayed inside a `<frame>`,
    /// `<iframe>`, `<embed>` or `<object>`.
    ///
    /// Common values:
    /// - [`DENY`]
    /// - [`SAMEORIGIN`]
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Frame-Options>
    (X_FRAME_OPTIONS, "x-frame-options");

    /// Defines a Content Security Policy (CSP).
    ///
    /// Specification:
    /// <https://www.w3.org/TR/CSP3/>
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/CSP>
    (CONTENT_SECURITY_POLICY, "content-security-policy");

    /// Content Security Policy in report-only mode.
    ///
    /// Violations are reported without blocking resource loading.
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only>
    (CONTENT_SECURITY_POLICY_REPORT_ONLY, "content-security-policy-report-only");

    /// Enables HTTP Strict Transport Security (HSTS).
    ///
    /// Specification:
    /// <https://www.rfc-editor.org/rfc/rfc6797>
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/Strict-Transport-Security>
    (STRICT_TRANSPORT_SECURITY, "strict-transport-security");

    /// Specifies how much referrer information is included with requests.
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/Referrer-Policy>
    (REFERRER_POLICY, "referrer-policy");

    /// Controls browser access to device capabilities and powerful features.
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/Permissions-Policy>
    (PERMISSIONS_POLICY, "permissions-policy");

    /// Cross-Origin Embedder Policy (COEP).
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy>
    (CROSS_ORIGIN_EMBEDDER_POLICY, "cross-origin-embedder-policy");

    /// Cross-Origin Opener Policy (COOP).
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy>
    (CROSS_ORIGIN_OPENER_POLICY, "cross-origin-opener-policy");

    /// Cross-Origin Resource Policy (CORP).
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy>
    (CROSS_ORIGIN_RESOURCE_POLICY, "cross-origin-resource-policy");

    /// Requests that the browser isolates this origin into its own process.
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/Origin-Agent-Cluster>
    (ORIGIN_AGENT_CLUSTER, "origin-agent-cluster");

    /// Restricts Adobe Flash and Acrobat cross-domain policies.
    ///
    /// Documentation:
    /// <https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Permitted-Cross-Domain-Policies>
    (X_PERMITTED_CROSS_DOMAIN_POLICIES, "x-permitted-cross-domain-policies");

    /// Prevents Internet Explorer from opening downloads directly.
    ///
    /// Documentation:
    /// <https://learn.microsoft.com/archive/blogs/ieinternals/ie8-security-part-v-comprehensive-protection>
    (X_DOWNLOAD_OPTIONS, "x-download-options");

    // =========================================================================
    // Cache
    // =========================================================================

    /// Indicates how a response interacted with caches.
    ///
    /// Specification:
    /// <https://www.rfc-editor.org/rfc/rfc9211>
    (CACHE_STATUS, "cache-status");

    /// Controls caching behavior for surrogate caches such as CDNs.
    (SURROGATE_CONTROL, "surrogate-control");

    /// Associates one or more cache invalidation tags with a response.
    (SURROGATE_KEY, "surrogate-key");

    // =========================================================================
    // Rate Limiting
    // =========================================================================

    /// Maximum number of requests permitted in the current window.
    ///
    /// Specification:
    /// <https://www.rfc-editor.org/rfc/rfc9333>
    (RATE_LIMIT_LIMIT, "ratelimit-limit");

    /// Remaining requests in the current rate limit window.
    ///
    /// Specification:
    /// <https://www.rfc-editor.org/rfc/rfc9333>
    (RATE_LIMIT_REMAINING, "ratelimit-remaining");

    /// Time until the current rate limit window resets.
    ///
    /// Specification:
    /// <https://www.rfc-editor.org/rfc/rfc9333>
    (RATE_LIMIT_RESET, "ratelimit-reset");

    /// Legacy compatibility header.
    (X_RATE_LIMIT_LIMIT, "x-ratelimit-limit");

    /// Legacy compatibility header.
    (X_RATE_LIMIT_REMAINING, "x-ratelimit-remaining");

    /// Legacy compatibility header.
    (X_RATE_LIMIT_RESET, "x-ratelimit-reset");

    /// Indicates how long a client should wait before retrying a request.
    ///
    /// Specification:
    /// <https://www.rfc-editor.org/rfc/rfc9110#field.retry-after>
    ///
    /// Example:
    /// ```http
    /// Retry-After: 120
    /// ```
    (RETRY_AFTER, "retry-after");
}

header_values! {
    // =========================================================================
    // Content Types
    // =========================================================================

    /// HTML document encoded as UTF-8.
    (CONTENT_TYPE_HTML, "text/html; charset=utf-8");

    /// Plain text encoded as UTF-8.
    (CONTENT_TYPE_TEXT, "text/plain; charset=utf-8");

    /// JSON encoded as UTF-8.
    (CONTENT_TYPE_JSON, "application/json; charset=utf-8");

    /// XML encoded as UTF-8.
    (CONTENT_TYPE_XML, "application/xml; charset=utf-8");

    /// JavaScript.
    (CONTENT_TYPE_JAVASCRIPT, "application/javascript; charset=utf-8");

    /// CSS stylesheet encoded as UTF-8.
    (CONTENT_TYPE_CSS, "text/css; charset=utf-8");

    /// SVG image.
    (CONTENT_TYPE_SVG, "image/svg+xml");

    /// Web App Manifest.
    (CONTENT_TYPE_MANIFEST, "application/manifest+json");

    /// WebAssembly binary.
    (CONTENT_TYPE_WASM, "application/wasm");

    /// Generic binary stream.
    (CONTENT_TYPE_OCTET_STREAM, "application/octet-stream");

    /// Event stream used by Server-Sent Events.
    (CONTENT_TYPE_EVENT_STREAM, "text/event-stream");

    /// Multipart byte ranges.
    (CONTENT_TYPE_MULTIPART_BYTERANGES, "multipart/byteranges");

    // =========================================================================
    // Cache-Control
    // =========================================================================

    /// Disables all caching.
    ///
    /// RFC 9111:
    /// <https://www.rfc-editor.org/rfc/rfc9111>
    (NO_STORE, "no-store");

    /// Requires caches to revalidate before reuse.
    (NO_CACHE, "no-cache");

    /// Marks the response as cacheable by any cache.
    (PUBLIC, "public");

    /// Marks the response as cacheable only by the client.
    (PRIVATE, "private");

    /// Prevents caches from transforming the payload.
    (NO_TRANSFORM, "no-transform");

    /// Indicates the response never changes.
    (IMMUTABLE, "public, max-age=31536000, immutable");

    /// Immediately expires the response.
    (MAX_AGE_0, "max-age=0");

    // =========================================================================
    // X-Frame-Options
    // =========================================================================

    /// Never allow framing.
    (DENY, "DENY");

    /// Allow framing only from the same origin.
    (SAMEORIGIN, "SAMEORIGIN");

    // =========================================================================
    // X-Content-Type-Options
    // =========================================================================

    /// Disable MIME sniffing.
    (NOSNIFF, "nosniff");

    // =========================================================================
    // Referrer Policy
    // =========================================================================

    (NO_REFERRER, "no-referrer");
    (NO_REFERRER_WHEN_DOWNGRADE, "no-referrer-when-downgrade");
    (ORIGIN, "origin");
    (ORIGIN_WHEN_CROSS_ORIGIN, "origin-when-cross-origin");
    (SAME_ORIGIN, "same-origin");
    (STRICT_ORIGIN, "strict-origin");
    (STRICT_ORIGIN_WHEN_CROSS_ORIGIN, "strict-origin-when-cross-origin");
    (UNSAFE_URL, "unsafe-url");

    // =========================================================================
    // Cross-Origin-Embedder-Policy
    // =========================================================================

    (REQUIRE_CORP, "require-corp");
    (CREDENTIALLESS, "credentialless");

    // =========================================================================
    // Cross-Origin-Opener-Policy
    // =========================================================================

    (UNSAFE_NONE, "unsafe-none");
    (SAME_ORIGIN_ALLOW_POPUPS, "same-origin-allow-popups");

    // =========================================================================
    // Cross-Origin-Resource-Policy
    // =========================================================================

    (CROSS_ORIGIN, "cross-origin");

    // =========================================================================
    // Permissions Policy
    // =========================================================================

    /// Empty permissions policy.
    (PERMISSIONS_NONE, "()");

    // =========================================================================
    // Strict-Transport-Security
    // =========================================================================

    /// One year HSTS.
    (HSTS_1_YEAR, "max-age=31536000");

    /// Two years with subdomains.
    (HSTS_2_YEARS_INCLUDE_SUBDOMAINS,
        "max-age=63072000; includeSubDomains");

    /// Two years, subdomains and preload.
    (HSTS_PRELOAD,
        "max-age=63072000; includeSubDomains; preload");

    // =========================================================================
    // Common Encodings
    // =========================================================================

    (GZIP, "gzip");
    (BR, "br");
    (DEFLATE, "deflate");
    (IDENTITY, "identity");

    // =========================================================================
    // Connection
    // =========================================================================

    (KEEP_ALIVE, "keep-alive");
    (CLOSE, "close");

    // =========================================================================
    // Upgrade
    // =========================================================================

    (WEBSOCKET, "websocket");
    (H2C, "h2c");

    // =========================================================================
    // Range Requests
    // =========================================================================

    (RANGE_BYTES, "bytes");
    (RANGE_NONE, "none");

    // =========================================================================
    // Expect
    // =========================================================================

    (CONTINUE_100, "100-continue");

    // =========================================================================
    // Miscellaneous
    // =========================================================================

    (ENCODING_CHUNKED, "chunked");
}
