[package]
name = "ophan"
version = "0.1.14"
edition = "2024"

[dependencies]
ophan-net = { path = "../libs/ophan-net" }
ophan-auth = { path = "../libs/ophan-auth" }
ophan-waf = { path = "../libs/ophan-waf" }
ophan-static = { path = "../libs/ophan-static" }
ophan-router = { path = "../libs/ophan-router" }

pingora = { workspace = true, features = ["proxy", "s2n"] }
tokio = { workspace = true }
tokio-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
mime_guess = { workspace = true }
memmap2 = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
regex = { workspace = true }
sha2 = { workspace = true }
memchr = { workspace = true }
http = { workspace = true }

aho-corasick = { workspace = true }

uuid = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }

async-trait = { workspace = true }
bytes = { workspace = true }

hashbrown = { workspace = true }
dashmap = { workspace = true }
arc-swap = { workspace = true }
parking_lot = { workspace = true }
ahash = { workspace = true }

## Used for loggs
tracing = { workspace = true, features = [
    "max_level_debug",
    "release_max_level_warn",
] }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { version = "~0.31.1", default-features = false, features = [
    "signal",
    "user",
] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_System_Threading",
    "Win32_Foundation",
] }

[dev-dependencies]
httpmock = "0.8.3"
rayon = { workspace = true }
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3"
reqwest = { version = "0.12", features = ["blocking"] }
