[package]
name = "ophan"
version = "0.1.24"
edition = "2024"

[dependencies]
ophan-net = { workspace = true }
ophan-auth = { workspace = true }
ophan-sec = { workspace = true }
ophan-static = { workspace = true }
ophan-router = { workspace = true }

flatkit = { workspace = true }
cli = { workspace = true }

pingora = { workspace = true, features = ["proxy", "s2n", "connection_filter"] }
futures = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["time"] }
regex = { workspace = true }
http = { workspace = true }

uuid = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
serde = { workspace = true }

async-trait = { workspace = true }
bytes = { workspace = true }
base64 = { workspace = true }

hashbrown = { workspace = true }
dashmap = { workspace = true }
arc-swap = { workspace = true }
ahash = { workspace = true }
memchr = { workspace = true }

## Used for loggs
tracing = { workspace = true, features = [
    "max_level_debug",
    "release_max_level_warn",
] }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { version = "~0.31.1", default-features = false, features = [
    "signal",
    "user",
] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_System_Threading",
    "Win32_Foundation",
] }

[[bench]]
name = "load-balancer"
harness = false

[[bench]]
name = "ref_or_copy"
harness = false

[[bench]]
name = "upstream_lookup"
harness = false

[[bench]]
name = "url_rewriting"
harness = false

[dev-dependencies]
httpmock = "0.8.3"
rayon = { workspace = true }
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3"
reqwest = { version = "0.12", features = ["blocking"] }
serde_json = { workspace = true }
